### ISSUE TITLE
A more portable signup/onboarding

### ISSUE THREAD

**Issue by nicola** [linkeddata/signup#1]
I found this to be the most powerful tool, since it allows users to log-in with any WebID in any platform supporting it.

I believe this should be ported in a way so that anyone could start to use it. The idea of using angular and jQuery is great, but what if it was a custom element/vanillajs implementation that can be used anywhere and styled by the provider?

I would like to volounteer to do so.

**Comment by deiu** [comment]
Implemented in 00f3fd3b37b241e26d2b3e13f9721fb3747ed93d
